name: Scheduled Cron Job

# Controls when the workflow will run
on:
  schedule:
    # Run daily at midnight
    - cron: '0 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run the script (you can modify this to run a different script)
      - name: Run Scheduled Script
        run: echo "Scheduled task executed"





